### ISSUE TITLE
ASCII view font in FSV not monospaced

### ISSUE THREAD

**Issue by ProfessorO** [dakotacookenmaster/metadisk#6]
I suspect the NUL character and other special characters in the weird old IBM character set are messing things up. I'd rather have nicely lined up text than the fancy characters.

**Comment by ProfessorO** [comment]
https://unifoundry.com/unifont might be useful

**Comment by dakotacookenmaster** [comment]
I have taken a lot of time to think about this, because readability is something that's especially important to me for this app.

Existing Issues:

- Supported fonts for the IBM PC Code Page 437 style are extremely hard to come by
- The current font selections for the ASCII layout were hand-picked and took hours to incorportate

As I mentioned, ease of use and readability is still very important to me. Thus, scenarios in which someone might want nice alignment for text (like viewing directories) should have their own specialized view. I'll endeavor to add those views. That way, the only time someone would be looking at the ASCII view (aside from simply to show how something might be represented) is when you're looking at a real file with ASCII-encoded data.

I think this is a reasonable compromise. I'm going to close this issue, but feel free to reopen if you have any ideas that might further improve this.
